version: '3'

services:
    mariadb:
        image: mariadb:10.6
        container_name: mysqldb
        restart: always
        command: --character_set_client=utf8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --character-set-client-handshake=FALSE
        volumes:
          - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: mysql123r
            MYSQL_DATABASE: dolibarr
            MYSQL_USER: dolibarr
            MYSQL_PASSWORD: dolibarr#123

    dolibarr:
        build: ./docker/php/
        container_name: dolibarr
        extra_hosts: 
            - "host.docker.internal:192.168.32.1"    # muy importante vincular con el gatewar del ifconfig de docker0
        restart: always
        environment:
           # XDEBUG_MODE: "${XDEBUG_MODE}"
            DOLI_DB_HOST: mariadb
            DOLI_DB_USER: dolibarr
            DOLI_DB_PASSWORD: dolibarr#123
            DOLI_DB_NAME: dolibarr
            DOLI_URL_ROOT: 'http://localhost:8080'
            PHP_INI_DATE_TIMEZONE: 'America/Mexico_City'
            DOLI_ADMIN_LOGIN: Administrador
            DOLI_ADMIN_PASSWORD: Administrador123#
        ports:
            - "8080:80"
          #  - "9003:9003"
        links:
            - mariadb
        volumes:
            - ./code:/var/www/html
            - ./documents:/var/www/documents
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
            - ./tmp:/tmp/xdebug
            #- ./code:/home
            
#volumes:
#    dolibarr_html:
#    dolibarr_docs:
#   dolibarr_db: